<?php

$labels = array();
$labels['vacation'] = 'Férias';
$labels['vacationenable'] = 'Habilitar';
$labels['vacationsubject'] = 'Assunto';
$labels['vacationmessage'] = 'Menssagem';
$labels['vacationforwarder'] = 'E-mail de encaminhamento';
$labels['vacationstart'] = 'Início';
$labels['vacationend'] = 'Fim';
$labels['period'] = 'Período';
$labels['frequency'] = 'Frequência';
$labels['addressed_to'] = 'Endereçado a';
$labels['append_subject'] = 'Acrescentar ao assunto original';
$labels['send_from'] = 'Enviado de';
$labels['vacationfrom'] = 'De';
$labels['vacationto'] = 'Para';
$labels['answer_no_more_than_every'] =  'Não responder mais do que a cada';
$labels['vacationdays'] = 'dias';
$labels['wholeday'] = 'Dia inteiro';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Selecione uma data inicial válida.';
$messages['vacationinvalidenddate'] = 'Selecione uma data final válida';
$messages['vacationinvaliddateinterval'] = 'O intervalo de data não é válido.';
$messages['vacationnosubject'] = 'Por favor preencha o assunto.';
$messages['vacationnomessage'] = 'Por favor preencha com a mensagem';
$messages['vacationinvalidforwarder'] = 'O endereço de encaminhamento não é válido.';
$messages['vacationinvalidforwarders'] = 'O endereço de encaminhamento não é válido.';
$messages['vacationdriverdefaulterror'] = 'Erro de execução desconhecido.';
$messages['vacationdriverconnecterror'] = 'Erro de conexão';
$messages['vacationdriverprocesserror'] = 'Erro durante o processamento';

?>
